### ISSUE TITLE
Char 0D inserted at the end of line

### ISSUE THREAD

**Issue by bruno185** [dfgordon/vscode-language-applesoft#1]
First of all, congratulations for this superb work.

I noticed a problem using this plugin:
Either simple program :
5 PRINT "AAAA"
10 END
If I transfer this program with AppleWin, as indicated in the documentation, I notice a line break between each line of the BASIC program, when listed. In this case between line 5 and line 10. When I inspect the memory from $801 onwards, I see a 'OD' (line feed) character.  This character causes a syntax error, when the program is run. I also tried to copy file using the "Save program to disk image" option : same result.

I use latest version of VS Code an AppleWin, on Windows 11 pro.

Here is a memory dump of the memory for the above comment :

<img width="642" alt="applesoft" src="https://user-images.githubusercontent.com/37832013/230734586-4ac42709-cd56-4bb9-a39f-e9d505154375.png">

**Comment by dfgordon** [comment]
Thanks for catching that.  I think it is happening whenever the source file uses `CRLF` as the line terminator.  You can also see this by using the `show tokenized code` command.  I'll try to patch as soon as I can.  As a workaround try changing to `LF` (toward the right of the bottom toolbar) and see if the `0D` goes away.

**Comment by dfgordon** [comment]
Version 1.1.2 is now available and should fix the issue.

**Comment by bruno185** [comment]
Thanks for your intervention on the code, the plugin works well now !
Indeed, vs code on Windows uses CRLF at the end of the line, as most
software do on Windows.
The best workaround is to copy the text and paste it in Applewin.

Sincerely,
